//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.SALARY_DETAIL = new HashSet<SALARY_DETAIL>();
        }
    
        public int EMPLOYEEID { get; set; }
        public int POSITIONID { get; set; }
        public int DEPARTMENTID { get; set; }
        public string FULLNAME { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public string ADDRESS { get; set; }
        public System.DateTime DATESTARTWORKING { get; set; }
        public string SEX { get; set; }
        public decimal PHONE { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual POSITION POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALARY_DETAIL> SALARY_DETAIL { get; set; }
    }
}
